config/routes.rb
Rails.application.routes.draw do
  root to: 'home_pages#show'

  resources :sounds, only: :show do
    collection do
      get 'waveforms'
    end
  end

  namespace :admin do
    resources :artists
    resources :sounds do
      get 'reprocess_mp3', on: :member
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < Forest::ApplicationRecord
  include Sluggable

  validates :name, presence: true

  def self.resource_description
    'Alias names'
  end
end

app/models/media_item.rb
require "mp3info"

class MediaItem < Forest::ApplicationRecord
  include BaseMediaItem

  def after_save_callbacks
    reprocess_sound_metadata
  end

  def reprocess_sound_metadata
    return unless self.attachment_content_type == 'audio/mpeg'

    mp3_info = Mp3Info.open(URI.open(self.attachment.url))
    json = mp3_info.as_json.except(*['tag2', 'tag3', 'tag4', 'tag5'])
    self.update(sound_metadata: json)
  end
end

app/models/sound.rb
class Sound < Forest::ApplicationRecord
  include Sluggable
  include Statusable

  belongs_to :artist
  belongs_to :media_item

  validates :title, :artist, :date, :stars, presence: true

  scope :by_date, -> { order(date: :desc, id: :desc) }

  def self.resource_description
    'Is it music?'
  end

  def slug_attribute
    "#{id} #{title}"
  end

  def duration
    seconds = media_item.sound_metadata.try(:[], 'length').to_i || 0
    [seconds / 3600, seconds / 60 % 60, seconds % 60].map { |t| t.to_s.rjust(2,'0') }.join(':').sub(/^00:/, '')
  end
end

app/controllers/admin/artists_controller.rb
class Admin::ArtistsController < Admin::ForestController
  before_action :set_artist, only: [:edit, :update, :destroy]

  def index
    @pagy, @artists = pagy apply_scopes(Artist).by_id
    authorize @artists, :admin_index?
  end

  def new
    @artist = Artist.new
    authorize @artist
  end

  def edit
    authorize @artist
  end

  def create
    @artist = Artist.new(artist_params)
    authorize @artist

    if @artist.save
      redirect_to edit_admin_artist_path(@artist), notice: 'Artist was successfully created.'
    else
      render :new
    end
  end

  def update
    authorize @artist

    if @artist.update(artist_params)
      redirect_to edit_admin_artist_path(@artist), notice: 'Artist was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @artist
    @artist.destroy
    redirect_to admin_artists_url, notice: 'Artist was successfully destroyed.'
  end

  private

  def artist_params
    # Add blockable params to the permitted attributes if this record is blockable `**BlockSlot.blockable_params`
    params.require(:artist).permit(:slug, :name, :description)
  end

  def set_artist
    @artist = Artist.find(params[:id])
  end
end

app/controllers/admin/sounds_controller.rb
class Admin::SoundsController < Admin::ForestController
  before_action :set_sound, only: [:edit, :update, :destroy, :reprocess_mp3]

  def index
    @pagy, @sounds = pagy apply_scopes(Sound).by_date
    authorize @sounds, :admin_index?
  end

  def new
    @sound = Sound.new
    authorize @sound
  end

  def edit
    authorize @sound
  end

  def reprocess_mp3
    authorize @sound, :edit?

    if @sound.media_item.reprocess_sound_metadata
      redirect_to edit_admin_sound_path(@sound), notice: 'Sound mp3 was successfully reprocessed.'
    else
      flash[:error] = 'Error reprocessing mp3'
      render :edit
    end
  end

  def create
    @sound = Sound.new(sound_params)
    authorize @sound

    if @sound.save
      redirect_to edit_admin_sound_path(@sound), notice: 'Sound was successfully created.'
    else
      render :new
    end
  end

  def update
    authorize @sound

    if @sound.update(sound_params)
      redirect_to edit_admin_sound_path(@sound), notice: 'Sound was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @sound
    @sound.destroy
    redirect_to admin_sounds_url, notice: 'Sound was successfully destroyed.'
  end

  private

  def sound_params
    # Add blockable params to the permitted attributes if this record is blockable `**BlockSlot.blockable_params`
    params.require(:sound).permit(:slug, :status, :title, :date, :media_item_id, :description, :waveform, :metadata, :artist_id, :stars)
  end

  def set_sound
    @sound = Sound.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_pages_controller.rb
class HomePagesController < PagesController
  def show
    super
    @sounds = Sound.by_date.published
  end
end

app/controllers/sounds_controller.rb
class SoundsController < ForestController
  before_action :set_sound, only: [:show]

  def show
    authorize @sound
  end

  def waveforms
    @sounds = Sound.all.published
    authorize @sounds
  end

  private

  def set_sound
    @sound = Sound.find_by!(slug: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/artists/_form.html.erb
<%= simple_form_for([:admin, @artist]) do |f| %>
  <%= f.error_notification %>
  <% if f.error(:base).present? && f.error(:base) != '<div></div>' %>
    <div class="mt-1 alert alert-danger w-100">
      <%= f.error(:base) %>
    </div>
  <% end %>
  <div class="row small-gutters">
    <%= render 'admin/shared/edit/sidebar', f: f, record: @artist %>
    <div class="col-md-9">
      <div class="card">
        <h1 class="h2 card-header"><%= record_name(@artist) %></h1>
        <div class="card-body">
          <div class="form-inputs">
            <div class="row small-gutters">
              <div class="col-md-6">
                <%= f.input :name %>
                <%= render 'admin/form_inputs/slug', f: f %>
              </div>
              <div class="col-md-6">
                <%= f.input :description, markdown: true %>
                <%= f.button :submit, class: 'btn-success d-md-none' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/artists/_table.html.erb
<div class="table-responsive">
  <%= content_tag :table, class: 'forest-table table table-striped table-sm' do %>
    <thead>
      <tr>
        <% if Artist.statusable? %>
          <th></th>
        <% end %>
        <th><%= table_sorter title: 'ID', path: :admin_artists_path, scope: :by_id, default_order: :desc %></th>
        <th><%= table_sorter title: 'Slug', path: :admin_artists_path, scope: :by_slug, default_order: :asc %></th>
        <th>Name</th>
        <th>Description</th>
        <th><%= table_sorter title: 'Created&nbsp;at'.html_safe, path: :admin_artists_path, scope: :by_created_at, default_order: :desc %></th>
        <th><%= table_sorter title: 'Updated&nbsp;at'.html_safe, path: :admin_artists_path, scope: :by_updated_at, default_order: :desc %></th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% records.each do |artist| %>
        <%= content_tag :tr do %>
          <% if Artist.statusable? %>
            <td><%= status_indicator artist %></td>
          <% end %>
          <td><%= artist.id %></td>
          <td><%= artist.slug %></td>
          <td><%= artist.name %></td>
          <td><%= artist.description %></td>
          <td><%= forest_date artist.created_at %></td>
          <td><%= forest_date artist.updated_at %></td>
          <td width="1">
            <%= link_to 'Edit', edit_admin_artist_path(artist), class: 'btn btn-xs btn-primary', role: 'button' %>
          </td>
          <% if try('artist_path', artist) %>
            <% if artist.respond_to?(:to_friendly_param) %>
              <% param = artist.to_friendly_param %>
            <% else %>
              <% param = artist %>
            <% end %>
            <td width="1">
              <%= link_to 'Show', artist_path(param), class: 'btn btn-xs btn-info', role: 'button', data: { turbolinks: false } %>
            </td>
          <% end %>
          <td width="1">
            <%= link_to 'Destroy', [:admin, artist], method: :delete, class: 'btn btn-xs btn-danger', role: 'button', data: { confirm: 'Are you sure you want to destroy this Artist?' } %>
          </td>
        <% end %>
      <% end %>
    </tbody>
  <% end %>
</div>

<%= pagy_bootstrap_nav_js(pagy).html_safe if pagy.pages > 1 %>

app/views/admin/artists/edit.html.erb
<%= render 'admin/headers/edit', record: @artist %>

<%= render 'form', record: @artist %>

app/views/admin/artists/index.html.erb
<%= render 'admin/headers/index', records: @artists, model_name: 'Artist' %>
<%= render 'admin/artists/table', records: @artists, pagy: @pagy %>

app/views/admin/artists/new.html.erb
<%= render 'admin/headers/edit', record: @artist %>

<%= render 'form', artist: @artist %>

app/views/admin/dashboard/index.html.erb
<% cache application_cache_key, expires_in: 4.weeks do %>
  <%= render 'admin/shared/breadcrumbs' %>
  <div class="card mb-3">
    <h1 class="card-header h2 border-bottom-0 d-flex align-items-center">
      Sounds
      <span class="h3 my-0 ml-auto">Forest CMS</span>
    </h1>
  </div>
  <% @_rendered_resources = [] %>
  <%= render 'admin/dashboard/panel',
             title: 'Content',
             resources: [Page, MediaItem, Menu, Setting] %>
  <%= render 'admin/dashboard/panel',
             title: 'Sounds',
             resources: [Sound, Artist] %>
  <%= render 'admin/dashboard/panel',
             title: 'Users',
             resources: [User, UserGroup] %>
  <%= render 'admin/dashboard/panel',
             title: 'Admin',
             resources: @admin_resources - @_rendered_resources %>
<% end %>

app/views/admin/sounds/_form.html.erb
<%= simple_form_for([:admin, @sound]) do |f| %>
  <%= f.error_notification %>
  <% if f.error(:base).present? && f.error(:base) != '<div></div>' %>
    <div class="mt-1 alert alert-danger w-100">
      <%= f.error(:base) %>
    </div>
  <% end %>
  <div class="row small-gutters">
    <%= render 'admin/shared/edit/sidebar', f: f, record: @sound %>
    <div class="col-md-9">
      <div class="card">
        <h1 class="h2 card-header"><%= record_name(@sound) %></h1>
        <div class="card-body">
          <div class="form-inputs">
            <div class="row small-gutters">
              <div class="col-md-6">
                <%= f.input :title %>
                <%= f.association :artist %>
                <%= render 'admin/form_inputs/slug', f: f %>
                <%= f.input :date, as: :datepicker %>
                <%= f.input :description, markdown: true %>
              </div>
              <div class="col-md-6">
                <%= render 'admin/form_inputs/status', f: f, record: @sound %>
                <%= f.association :media_item, label: 'mp3 File', remote: { path: admin_media_items_path(audio: true) } %>
                <%= f.input :stars %>
                <%= f.input :waveform %>
                <% if f.object.waveform.blank? && !@sound.new_record? %>
                  <%= link_to 'Create waveform!', sound_path(@sound.to_friendly_param), target: '_blank', class: 'btn btn-primary' %>
                <% end %>
                <%= f.button :submit, class: 'btn-success d-md-none' %>
              </div>
            </div>
            <% unless f.object.new_record? %>
              <hr>
              <div class="row small-gutters">
                <div class="col">
                  <%= link_to 'Reprocess media item mp3 metadata', reprocess_mp3_admin_sound_path, target: '_blank', class: 'btn btn-secondary' %>
                  <pre>
                    <code>
  <%= JSON.pretty_generate(f.object.try(:media_item).try(:sound_metadata)) %>
                    </code>
                  </pre>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/sounds/_table.html.erb
<div class="table-responsive">
  <%= content_tag :table, class: 'forest-table table table-striped table-sm' do %>
    <thead>
      <tr>
        <% if Sound.statusable? %>
          <th></th>
        <% end %>
        <th><%= table_sorter title: 'ID', path: :admin_sounds_path, scope: :by_id, default_order: :desc %></th>
        <th><%= table_sorter title: 'Slug', path: :admin_sounds_path, scope: :by_slug, default_order: :asc %></th>
        <th>Title</th>
        <th>Artist</th>
        <th>Date</th>
        <th>TR Words</th>
        <th>Waveform</th>
        <th>Metadata</th>
        <th><%= table_sorter title: 'Created&nbsp;at'.html_safe, path: :admin_sounds_path, scope: :by_created_at, default_order: :desc %></th>
        <th><%= table_sorter title: 'Updated&nbsp;at'.html_safe, path: :admin_sounds_path, scope: :by_updated_at, default_order: :desc %></th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% records.includes(:artist).each do |sound| %>
        <%= content_tag :tr do %>
          <% if Sound.statusable? %>
            <td><%= status_indicator sound %></td>
          <% end %>
          <td><%= sound.id %></td>
          <td><%= sound.slug %></td>
          <td><%= sound.title %></td>
          <td><%= sound.artist.try(:name) %></td>
          <td><%= sound.date %></td>
          <td><%= sound.description.split(' ').length %> words</td>
          <td><%= sound.waveform.present? ? '✅' : '⚠️' %></td>
          <td><%= sound.media_item.sound_metadata.present? ? '✅' : '⚠️' %></td>
          <td><%= forest_date sound.created_at %></td>
          <td><%= forest_date sound.updated_at %></td>
          <td width="1">
            <%= link_to 'Edit', edit_admin_sound_path(sound), class: 'btn btn-xs btn-primary', role: 'button' %>
          </td>
          <% if try('sound_path', sound) %>
            <% if sound.respond_to?(:to_friendly_param) %>
              <% param = sound.to_friendly_param %>
            <% else %>
              <% param = sound %>
            <% end %>
            <td width="1">
              <%= link_to 'Show', sound_path(param), class: 'btn btn-xs btn-info', role: 'button', data: { turbolinks: false } %>
            </td>
          <% end %>
          <td width="1">
            <%= link_to 'Destroy', [:admin, sound], method: :delete, class: 'btn btn-xs btn-danger', role: 'button', data: { confirm: 'Are you sure you want to destroy this Sound?' } %>
          </td>
        <% end %>
      <% end %>
    </tbody>
  <% end %>
</div>

<%= pagy_bootstrap_nav_js(pagy).html_safe if pagy.pages > 1 %>

app/views/admin/sounds/edit.html.erb
<%= render 'admin/headers/edit', record: @sound %>

<%= render 'form', record: @sound %>

app/views/admin/sounds/index.html.erb
<%= render 'admin/headers/index', records: @sounds, model_name: 'Sound' %>
<%= render 'admin/sounds/table', records: @sounds, pagy: @pagy %>

app/views/admin/sounds/new.html.erb
<%= render 'admin/headers/edit', record: @sound %>

<%= render 'form', sound: @sound %>

app/views/home_pages/show.html.erb
<% cache [@page, application_cache_key], expires_in: 4.weeks do %>
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <table class="sounds-table">
          <tr>
            <th></th>
            <th>Date</th>
            <th>Title</th>
            <th>Alias</th>
            <th>TR&nbsp;Words</th>
            <th class="d-none d-md-block">Rating</th>
            <th>Duration</th>
            <th>
              <div class="d-md-none">Audio</div>
              <div class="d-none d-md-block">Topography</div>
            </th>
          </tr>
          <% @sounds.includes(:artist, :media_item).each do |sound| %>
            <%= content_tag :tr, class: 'sound-wrapper', data: { id: sound.id } do %>
              <td>
                <button class="play-sound-button">Play</button>
              </td>
              <td class="text-nowrap"><%= sound.date %></td>
              <td><%= link_to sound.title, sound.media_item.attachment.url, download: true, target: '_blank' %></td>
              <td class="text-nowrap">
                <%= content_tag :span, sound.artist.name %>
              </td>
              <td>
                <% if sound.description.present? %>
                  <%= link_to "TR-#{sound.description.split.length}", '#', class: 'tr-words-link' %>
                <% else %>
                  —
                <% end %>
              <td class="d-none d-md-block">
                <%= '★' * sound.stars + '☆' * (5 - sound.stars) %>
              </td>
              <td>
                <div class="sound-total-time">
                  <%= sound.duration %>
                </div>
                <div class="sound-current-time"></div>
              </td>
              <td>
                <%= content_tag :div, nil, class: 'sound w-100', data: { url: sound.media_item.attachment.url } %>
              </td>
            <% end %>
            <%= content_tag :tr, class: 'd-none sound-tr', data: { id: sound.id } do %>
              <td colspan="8" class="pb-3">
                <strong>Trip Report</strong>
                <br>
                <%= md sound.description %>
              </td>
            <% end %>
          <% end %>
        </table>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="no-js js-preload" lang="en" data-root-url="<%= root_url %>">
  <head>
    <%= render 'layouts/shared_head' %>
    <meta name="turbo-cache-control" content="no-cache">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= favicon_link_tag 'favicon.png', rel: 'icon', type: 'image/png' %>
    <%= javascript_include_tag 'application', defer: true %>
  </head>
  <body class="<%= @html_classes.try(:join, ' ') %>">
    <%= render 'shared/header' %>
    <main id="application-wrapper" class="application-wrapper d-flex flex-column">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_header.html.erb
<header id="header" class="header mt-2 mb-4">
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <h1>sounds.dylanfisher.com</h1>
      </div>
    </div>
  </div>
</header>

app/views/sounds/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div id="waveform-parent" class="col">
      <%= @sound.title %>
      <div id="waveform-loading-message">Loading waveform... this may take a minute.</div>
      <%= content_tag :div, nil, id: 'waveform', data: { url: @sound.media_item.attachment.url } %>
      <%= simple_form_for [:admin, @sound], html: { class: 'd-none' } do |f| %>
        <hr>
        Waveform:
        <%= f.input :waveform, label: false, input_html: { class: 'w-100' } %>
        <hr>
        <%= f.submit 'Upload waveform data to server' %>
      <% end %>
    </div>
  </div>
</div>